### ISSUE TITLE
29581765: Did end touch event called on background thread leading to crash

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#16499]
#### Description

Marked as a duplicate of 28223628
Based on the crashlytics stack trace i got for this crash, it appears to me that the touch notification for the gesture ending is called on a background thread and that is the source of the crash.

-
Product Version: iOS 10
Created: 2016-12-08T20:31:46.217300
Originated: 2016-12-08T00:00:00
Open Radar Link: http://www.openradar.me/29581765

**Comment by openradar-mirror** [comment]
Resolved: 12/14/2016
Modified: 2016-12-15T06:50:02.358850

**Comment by openradar-mirror** [comment]
Resolved: 12/14/2016
Modified: 2016-12-15T06:50:02.358850

**Comment by openradar-mirror** [comment]
Resolved: 12/14/2016
Modified: 2016-12-15T06:50:02.358850

**Comment by openradar-mirror** [comment]
Resolved: 12/14/2016
Modified: 2016-12-15T06:50:02.358850

**Comment by openradar-mirror** [comment]
Resolved: 12/14/2016
Modified: 2017-04-24T19:21:45.376640

**Comment by openradar-mirror** [comment]
Resolved: 12/14/2016
Modified: 2017-04-24T19:21:45.376640

**Comment by openradar-mirror** [comment]
Resolved: 12/14/2016
Modified: 2017-04-24T19:21:45.376640

**Comment by openradar-mirror** [comment]
Resolved: 12/14/2016
Modified: 2017-04-24T19:21:45.376640

**Comment by openradar-mirror** [comment]
Resolved: 12/14/2016
Modified: 2017-04-24T19:21:45.376640

**Comment by openradar-mirror** [comment]
Resolved: 12/14/2016
Modified: 2017-04-24T19:21:45.376640

**Comment by openradar-mirror** [comment]
Resolved: 12/14/2016
Modified: 2017-04-24T19:21:45.376640

**Comment by konradzuwala** [comment]
Is there any info how was this issue closed? Having currently same problem and looking for a solution.
