### ISSUE TITLE
31173967: Xcode_8.2.1 (8C1002): xcrun simctl io booted recordVideo generates glitchy video

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#17119]
#### Description

Summary:
The videos generated by xcrun simctl io booted recordVideo have several issues.

Steps to Reproduce:
1. Open the iOS simulator. In my testing, I used an iPhone 5 simulator running iOS 10.2 (14C89).
2. Open the Terminal.
3. Run `xcrun simctl io booted recordVideo ~/Desktop/test.mp4` in the Terminal.
4. Do some stuff in the simulator. Open apps, scroll things. Stuff that creates motion in the recording.
5. Hit ^C to stop recording.

Expected Results:
1. The video has a Quick Look preview on the desktop, just like other movies playable with QuickTime Player.
2. The video can be scrubbed in QuickTime Player with no glitches or artifacts.
3. The video can be scrubbed in QuickTime Player by two-finger dragging left and right on the trackpad.
4. The video can be trimmed in QuickTime Player with no glitches or artifacts.
5. The trimmed video can be saved.

Actual Results:
1. The video does not have a Quick Look preview on the Desktop, even after running `qlmanage -r` and restarting the Finder.
2. The video can be scrubbed in QuickTime Player, but it has really bad artifacting (see attached video).
3. The video cannot be scrubbed in QuickTime Player by two-finger dragging horizontally on the trackpad. The playhead remains resolutely immobile, even though I can easily scrub other videos, including the one attached to this radar.
4. When using QuickTime Player’s trimming feature (⌘T), dragging the in and out points results in the same glitching as when scrubbing through the video. The video also sometimes changes to almost completely green.
5. Saving the trimmed video always fails. There is first a brief error dialog that says “The operation could not be completed An unknown error occurred (-12769)”, which is on screen so quickly that I could only read it by looking at the screen recording I made. Then that error disappears, and is replaced with “The operation could not be completed.”

Regression:
Unknown.

Notes:
Testing on MacBook Pro (Retina, 15-inch, Late 2013) running 10.12.3 (16D32).
Screen recording to demonstrate this issue is attached, and also posted at https://cl.ly/jewz

-
Product Version: Xcode_8.2.1 (8C1002)
Created: 2017-03-21T17:34:36.857580
Originated: 2017-03-21T13:34:00
Open Radar Link: http://www.openradar.me/31173967

**Comment by openradar-mirror** [comment]
Resolved: 21-Mar-2017 03:32 PM
Modified: 2017-03-21T19:33:00.642790

**Comment by openradar-mirror** [comment]
Resolved: 21-Mar-2017 03:32 PM
Modified: 2017-03-21T19:33:00.642790

**Comment by openradar-mirror** [comment]
Resolved: 21-Mar-2017 03:32 PM
Modified: 2017-03-21T19:33:00.642790

**Comment by openradar-mirror** [comment]
Resolved: 21-Mar-2017 03:32 PM
Modified: 2017-03-21T19:33:00.642790

**Comment by SuttonKyle** [comment]
How was number 5 resolved?  I'm still having trouble saving trimmed videos.  Any help would be very very appreciated!
