### ISSUE TITLE
33565820: Xcode 9 beta 4 crashes when adding a project to an open workspace/project

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#18056]
#### Description

Summary:
When a project is added to an existing workspace or project, Xcode crashes.

Steps to Reproduce:
- Create a new project A in Xcode, close it.
- Create a new project B in Xcode
- Drag projectA.xcodeproj into the navigation pane of project B
- (alternatively) right click the navigation pane, "Add files…", and select projectA.xcodeproj

Expected Results:
Project A is added to Project B's hierarchy

Observed Results:
Xcode crashes immediately. On re-launch, Project B is unchanged (does not contain project A in the file hierarchy)

-
Product Version: Xcode 9.0 beta 4 (9M189t)
Created: 2017-07-27T13:00:10.318010
Originated: 2017-07-27T00:00:00
Open Radar Link: http://www.openradar.me/33565820

**Comment by mbroski** [comment]
Same thing is happening to me.  Anybody find a workaround?

**Comment by tiagoalexbastos** [comment]
same.

**Comment by mryraghi** [comment]
The same is happening to me. A workaround is to drag both the .xcodeproj and the related folder to the destination workspace/project and then remove the reference to the folder.

<img width="541" alt="screen shot 2017-08-21 at 17 36 14" src="https://user-images.githubusercontent.com/5071701/29526882-5cf3e4fa-8697-11e7-8294-f30efbf27f4a.png">

**Comment by openradar-mirror** [comment]
Resolved: No
Modified: 2017-09-08T09:22:15.093570

**Comment by openradar-mirror** [comment]
Resolved: No
Modified: 2017-09-08T09:22:15.093570
