### ISSUE TITLE
34099723: Xcode crashes when adding adding a project to a workspace

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#18254]
#### Description

Summary:
When adding a new xcodeproj to an xcworkspace, Xcode crashes.

Steps to Reproduce:
1. Create a new project A, save it as a new workspace with File -> Save as Workspace...
2. Create another new project B
3. Drag B into the A workspace

Expected Results:
The project is added to the workspace

Actual Results:
Xcode crashes

Version:
Xcode 9 beta 6

Notes:
See the attached project for an example, and the crashlog

-
Product Version: Xcode 9 beta 6
Created: 2017-08-27T00:01:25.466190
Originated: 2017-08-26T20:01:00
Open Radar Link: http://www.openradar.me/34099723

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by openradar-mirror** [comment]
Resolved: Assumably Xcode 9 beta 7
Modified: 2017-09-02T18:46:41.761430

**Comment by sstadelman** [comment]
For the hackiest workaround... open the `*.xcworkspace` in Xcode 8.x, drag the `*.xcodeproj` to its destination, then return to Xcode 9.beta-x.
