### ISSUE TITLE
34857036: LAContext.biometryType always return none

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#18584]
#### Description

Area:
Local Authentication Framework

Summary:
LAContext.biometryType always return none

Steps to Reproduce:
1. Get LAContext.biometryType for a device:
```
let myContext = LAContext()
switch myContext.biometryType {
case .none: print("None")
case .typeFaceID: print("FaceID")
case .typeTouchID: print("TouchID")
}
```
(Sample project: https://github.com/jsambuo/TestBiometryType)
2. Run on a simulator or device, and check the console.

Expected Results:
I should see "FaceID" in the console for the iPhone X simulator when Face ID is enrolled, and "TouchID" in the console for the iPhone 8 simulator when Touch ID is enrolled.

Actual Results:
"None" is printed.
Video: https://youtu.be/5ls4KwMNjRU

Version/Build:
Xcode 9.1 Beta (9B37)

Configuration:
iPhone X and iPhone 8 Plus Simulator.
I also see the same results for my iPhone 7 Plus (iOS 11.0.2)

-
Product Version: 11.1 (15B5066e)
Created: 2017-10-06T16:27:42.810340
Originated: 2017-10-06T00:00:00
Open Radar Link: http://www.openradar.me/34857036

**Comment by Soumin** [comment]
Always check canEvaluatePolicy before checking biometryType.

**Comment by openradar-mirror** [comment]
Resolved: Duplicate
Modified: 2017-11-07T18:45:12.987450

**Comment by openradar-mirror** [comment]
Resolved: Duplicate
Modified: 2017-11-07T18:45:12.987450

**Comment by openradar-mirror** [comment]
Resolved: Duplicate
Modified: 2017-11-07T18:45:12.987450
