### ISSUE TITLE
34911577: Unable to use spell check in Xcode 9

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#18618]
#### Description

Area:
Xcode

Summary:
Xcode 9 GM and Xcode 9.1 beta do not have the ability to enable spell checking. 

Steps to Reproduce:
Open the menu Edit > Format > Spelling and Grammar in Xcode 9.

Expected Results:
The menu options should be available.

Actual Results:
All the options within that menu are greyed out except "Show Spelling and Grammar". This was not the case in Xcode 8.

Other users have also noticed this:
https://forums.developer.apple.com/thread/88329

-
Product Version: 9
Created: 2017-10-10T16:11:08.216040
Originated: 2017-10-10T00:00:00
Open Radar Link: http://www.openradar.me/34911577

**Comment by openradar-mirror** [comment]
Resolved: No
Modified: 2017-10-13T08:58:58.084580

**Comment by emiliano1** [comment]
so no solution to this?

**Comment by ghost** [comment]
Any solution here?
