### ISSUE TITLE
35654790: Unable to capture view hierarchy

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#18931]
#### Description

Summary:
"Debug View Hierarchy" fails with some views with the error message "Unable to capture view hierarchy." This seems to have to do with the contents of the view, because view hierarchy debugging works if another view is opened, but breaks again as soon as the problematic view is shown. I did not succeed in isolating the problematic view, so I can't offer an example project.

What _doesn't_ fix the issue while showing the problematic view:
* restarting the simulator or the phone
* relaunching the app
* restarting Xcode

I haven't found a workaround yet (other than using Reveal, which works as expected). The issue first appeared after updating from Xcode 8 to Xcode 9.

Steps to Reproduce:
* Build and run iOS app in simulator or on device.
* In Xcode, click on "Debug View Hierarchy"

Expected Results:
The view hierarchy appears in Xcode.

Actual Results:
I get the following debugger output:

Error:    Unable to capture view hierarchy.
Details:  Log Title: Error generating request response data.
Log Details: Die Daten konnten nicht geschrieben werden, da im Inhalt der Daten ein Fehler aufgetreten ist.
Log Method: -[DBGTargetHub performRequest:]_block_invoke
Method:   -[DBGViewDebugger updateDebugHierarchy]_block_invoke_2

Version/Build:
Xcode Version 9.1 (9B55)
Mac OS 10.13.1 (17B48)
SimulatorApp-835.2.1
CoreSimulator-494.22.7

Configuration:
* simulated iPhone SE with iOS 11.1
* iPhone 6  with iOS 11.1.2 (15B202)

-
Product Version: Xcode 9 (9B55)
Created: 2017-11-21T09:47:29.698510
Originated: 2017-11-21T00:00:00
Open Radar Link: http://www.openradar.me/35654790

**Comment by openradar-mirror** [comment]
Resolved: fixed
Modified: 2018-01-31T08:03:19.273860

**Comment by openradar-mirror** [comment]
Resolved: fixed
Modified: 2018-01-31T08:03:19.273860

**Comment by openradar-mirror** [comment]
Resolved: fixed
Modified: 2018-01-31T08:03:19.273860

**Comment by ArtSabintsev** [comment]
Subscribing to this bug.
