### ISSUE TITLE
39386636: Image cursors on external displays broken by 10.13.4

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#19632]
#### Description

Users report the mouse cursor is invisible on external displays after upgrading to macOS 10.13.4. Adjusting the size of the cursor in system prefs works around the problem. Here are the reports:

https://gitlab.com/gnachman/iterm2/issues/6608
https://gitlab.com/gnachman/iterm2/issues/6623
https://gitlab.com/gnachman/iterm2/issues/6614

I have not been able to reproduce this myself. It appears that only cursors created with [NSCursor initWithImage:hotSpot:] are affected.

Steps to Reproduce:
1. Install iTerm2
2. Place window on external display
3. Move cursor to external display

Expected Results:
Mouse cursor is visible

Actual Results:
Mouse cursor not visible

Version/Build:
10.13.4

Configuration:

-
Product Version: 
Created: 2018-04-12T18:00:58.096510
Originated: 2018-04-12T00:00:00
Open Radar Link: http://www.openradar.me/39386636

**Comment by franckatwag** [comment]
Same issue with SublimeText. (https://github.com/SublimeTextIssues/Core/issues/2250). Temporary fix is to change cursor size in pref, accessibility, display.

**Comment by openradar-mirror** [comment]
Resolved: dup of 38782414
Modified: 2018-07-20T02:17:48.526120

**Comment by openradar-mirror** [comment]
Resolved: dup of 38782414
Modified: 2018-07-20T02:17:48.526120

**Comment by openradar-mirror** [comment]
Resolved: dup of 38782414
Modified: 2018-07-20T02:17:48.526120

**Comment by openradar-mirror** [comment]
Resolved: dup of 38782414
Modified: 2018-07-20T02:17:48.526120
