### ISSUE TITLE
40581820: MobileSafari crashes when I zoom out on this one website

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#19773]
#### Description

Summary:
When I zoom in to this website and then out again, MobileSafari’s current tab crashes.

https://uxdesign.cc/how-to-build-a-better-product-with-ux-writing-926d78209ce8

Steps to Reproduce:
1. Load this page in MobileSafari on an iPhone: https://uxdesign.cc/how-to-build-a-better-product-with-ux-writing-926d78209ce8
(I’ve tested on an iPhone X and an iPhone 6)
2. Pinch to zoom in, perhaps to read the small text.
3. Wait for the rendering to catch up.
4. Pinch again to zoom out.

Expected Results:
No crash.

Actual Results:
Crash as the page redraws.

Version:
iOS 11.3.1 (15E302)

Notes:
Attached screen recording also available at https://cl.ly/rsTY

Configuration:

-
Product Version: iOS 11.3.1 (15E302)
Created: 2018-05-26T21:50:16.787760
Originated: 2018-05-26T17:47:00
Open Radar Link: http://www.openradar.me/40581820

**Comment by CochiorasBogdan** [comment]
For me Safari didn't crash, the hole phone crashed, it restarted. iPhone 5S iOS 11.3.1

**Comment by openradar-mirror** [comment]
Resolved: June 13 2018, 12:53 PM
Modified: 2018-06-24T22:10:00.093643

**Comment by openradar-mirror** [comment]
Resolved: June 13 2018, 12:53 PM
Modified: 2018-06-24T22:10:00.093643

**Comment by openradar-mirror** [comment]
Resolved: June 13 2018, 12:53 PM
Modified: 2018-06-24T22:10:00.093643

**Comment by openradar-mirror** [comment]
Resolved: June 13 2018, 12:53 PM
Modified: 2018-06-24T22:10:00.093643

**Comment by openradar-mirror** [comment]
Resolved: June 13 2018, 12:53 PM
Modified: 2018-06-24T22:10:00.093643

**Comment by openradar-mirror** [comment]
Resolved: June 13 2018, 12:53 PM
Modified: 2018-06-24T22:10:00.093643
