### ISSUE TITLE
41828352: In iOS12 beta Calling UIGraphicsGetCurrentContext() in draw(_ rect: CGRect) returns a kCGContextTypeUnknown

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#20042]
#### Description

Area:
UIKit

Summary:
Calling UIGraphicsGetCurrentContext() in draw(_ rect: CGRect) returns a kCGContextTypeUnknown CGContext

Steps to Reproduce:
Call UIGraphicsGetCurrentContext() in draw(_ rect: CGRect)

Expected Results:
Return the current context.
 
Actual Results:
Returns a kCGContextTypeUnknown CGContext that seems to be useless (can't return any data about the context, even its width and height).

Version/Build:
iOS 12 beta 3

-
Product Version: 12 beta
Created: 2018-07-06T17:34:36.319760
Originated: 2018-07-04T00:00:00
Open Radar Link: http://www.openradar.me/41828352

**Comment by openradar-mirror** [comment]
Resolved: YES
Modified: 2018-07-26T15:46:18.440160

**Comment by openradar-mirror** [comment]
Resolved: YES
Modified: 2018-07-26T15:46:18.440160

**Comment by openradar-mirror** [comment]
Resolved: YES
Modified: 2018-07-26T15:46:18.440160

**Comment by TwoSunTraders** [comment]
Looks like this bug is back in iOS 12 GM
