### ISSUE TITLE
42559318: CAGradientLayer does not support Display P3/Wide Color

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#20152]
#### Description

Area:

Core Animation

Summary:

CAGradientLayer does not seem to support wide color.

Steps to Reproduce:

1. Create a CAGradientLayer
2. Set its colors to CGColors with a Display P3 color space
3. Note that the colors are rendered without wide color

Here's a code snippet I used to create the attached screenshot, which creates an all-pink "gradient."

```
let wideCGColor = CGColor(colorSpace: CGColorSpace(name: CGColorSpace.displayP3)!, components: [1, 0, 0.8, 1])!
let gradientLayer = CAGradientLayer()
gradientLayer.colors = [wideCGColor, wideCGColor]
gradientLayer.locations = [0, 1]
```

In attached the screenshot, I have a layer with the wide color being set as the background color, and the gradient layer underneath, which is noticeably "dull."

Expected Results:

The gradient layer should render wide colors as such.

Actual Results:

The gradient layer seems to ignore the wide color space.

Version/Build:

Xcode Version 10.0 beta 4 (10L213o)
iOS Version 12.0 beta 4 (16A5327f)

This behavior was also present in Xcode 9.3 building to an iOS 11 device.

-
Product Version: Version 10.0 beta 4 (10L213o)
Created: 2018-07-24T22:36:53.484250
Originated: 2018-07-24T00:00:00
Open Radar Link: http://www.openradar.me/42559318

**Comment by openradar-mirror** [comment]
Resolved: August 6, 2018
Modified: 2018-08-06T21:40:15.066350

**Comment by openradar-mirror** [comment]
Resolved: August 6, 2018
Modified: 2018-08-06T21:40:15.066350

**Comment by openradar-mirror** [comment]
Resolved: August 6, 2018
Modified: 2018-08-06T21:40:15.066350

**Comment by openradar-mirror** [comment]
Resolved: August 6, 2018
Modified: 2018-08-06T21:40:15.066350

**Comment by openradar-mirror** [comment]
Resolved: August 6, 2018
Modified: 2018-08-06T21:40:15.066350

**Comment by Arlomarlo18** [comment]
How did you solve this?
