### ISSUE TITLE
44755883: Import auto-completion crashes on relative paths in Xcode 10

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#20462]
#### Description

Summary:
When project settings contains relative paths like "../somedir" in either "Header Search Paths" or "User Header Search Paths" Xcode will crash when attempting to display suggestions for "#import".

Steps to Reproduce:
- create new project. For example, macOS console app
- select target
- under "Header Search Paths" add "../somedir"
- in "main.m" type "#import <>". Put cursor inside the brackets and start typing anything
- Xcode will crash

Expected Results:
Xcode suggesting header paths

Actual Results:
Xcode crashes with "Path must be absolute but is not: ../somedir"

Version/Build:
10.0 (10A255)

Configuration:
iMac mid 2011

-
Product Version: 10.0 (10A255)
Created: 2018-09-25T10:04:12.519807
Originated: 2018-09-25T00:00:00
Open Radar Link: http://www.openradar.me/44755883

**Comment by gerrybeauregard** [comment]
I ran into this crash a lot recently, but with help from a fellow developer (Alex Belov) fixed it using the $(PROJECT_DIR) environment variable. So in "Header Search Paths", instead of
   ../somedir
you would use
   $(PROJECT_DIR)/../somedir

**Comment by openradar-mirror** [comment]
Resolved: 10.1
Modified: 2018-12-04T09:58:31.157945

**Comment by openradar-mirror** [comment]
Resolved: 10.1
Modified: 2018-12-04T09:58:31.157945

**Comment by openradar-mirror** [comment]
Resolved: 10.1
Modified: 2018-12-04T09:58:31.157945

**Comment by openradar-mirror** [comment]
Resolved: 10.1
Modified: 2018-12-04T09:58:31.157945

**Comment by openradar-mirror** [comment]
Resolved: 10.1
Modified: 2018-12-04T09:58:31.157945

**Comment by openradar-mirror** [comment]
Resolved: 10.1
Modified: 2018-12-04T09:58:31.157945

**Comment by openradar-mirror** [comment]
Resolved: 10.1
Modified: 2018-12-04T09:58:31.157945
