### ISSUE TITLE
47482143: Xcode: non-printing characters are hard to deal with

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#20930]
#### Description

Summary:
Non-printing characters, especially in strings, are hard to notice, and can cause subtle bugs. Xcode should either show an error/warning in such cases, or should render these characters in a special way that makes it more obvious that they are present.

Steps to Reproduce:
1. Try to run this code:

let url = URL(string: "https://apple.com") // valid URL
let sadness = URL(string: "‌https://apple.com") // zero-width joiner at start of string, invalid URL

Expected Results:
It’s trivially easy to tell that the first string has all printing characters, and the second has a U+200D ZERO WIDTH NON-JOINER at the start. Xcode either shows a warning/error or renders the character as some kind of special glyph, maybe one that you can click on to get more info.

Actual Results:
Xcode does nothing to help you see what’s going on. Your only chance of noticing is either a) enumerating the string character-by-character, or b) using the arrow keys to move one character at a time.

Version:
Xcode 10.1 (10B61) on macOS 10.14.2 (18C54)

Notes:
Useful site for seeing non-printing characters in a string: https://www.soscisurvey.de/tools/view-chars.php.

-
Product Version: Xcode 10.1 (10B61) on macOS 10.14.2 (18C54)
Created: 2019-01-23T16:54:44.813122
Originated: 2019-01-23T11:54:00
Open Radar Link: http://www.openradar.me/47482143

**Comment by openradar-mirror** [comment]
Resolved: 24-Jan-2019 02:50 PM
Modified: 2019-01-26T16:35:04.688613

**Comment by openradar-mirror** [comment]
Resolved: 24-Jan-2019 02:50 PM
Modified: 2019-01-26T16:35:04.688613

**Comment by openradar-mirror** [comment]
Resolved: 24-Jan-2019 02:50 PM
Modified: 2019-01-26T16:35:04.688613

**Comment by openradar-mirror** [comment]
Resolved: 24-Jan-2019 02:50 PM
Modified: 2019-01-26T16:35:04.688613

**Comment by openradar-mirror** [comment]
Resolved: 24-Jan-2019 02:50 PM
Modified: 2019-01-26T16:35:04.688613

**Comment by openradar-mirror** [comment]
Resolved: 24-Jan-2019 02:50 PM
Modified: 2019-01-26T16:35:04.688613

**Comment by openradar-mirror** [comment]
Resolved: 24-Jan-2019 02:50 PM
Modified: 2019-01-26T16:35:04.688613

**Comment by openradar-mirror** [comment]
Resolved: 24-Jan-2019 02:50 PM
Modified: 2019-01-26T16:35:04.688613

**Comment by openradar-mirror** [comment]
Resolved: 24-Jan-2019 02:50 PM
Modified: 2019-01-26T16:35:04.688613

**Comment by openradar-mirror** [comment]
Resolved: 24-Jan-2019 02:50 PM
Modified: 2019-01-26T16:35:04.688613

**Comment by openradar-mirror** [comment]
Resolved: 24-Jan-2019 02:50 PM
Modified: 2019-01-26T16:35:04.688613

**Comment by openradar-mirror** [comment]
Resolved: 24-Jan-2019 02:50 PM
Modified: 2019-01-26T16:35:04.688613

**Comment by wving5** [comment]
How did this get fixed ❓ Maybe use of some 'low-level' tool like vim, git-diff or script detecting ?
