### ISSUE TITLE
23165183: Xcode 7.1b3: Frequent "Timeout waiting to launch Target Application" when running UI Tests

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#6463]
#### Description

Summary:
When running multiple UI tests Xcode 7.1 beta 3 (7B85) seems to lose communication with the simulator. A few tests will run normally and then after relaunching the app the simulator will just seem to sit idle and Xcode seems to just sit and wait. After a few moments Xcode reports a SIGKILL and the rest of the tests fail.

This wasn't happening in Xcode 7.0.1

Steps to Reproduce:
1) write multiple UI tests for an app (30-40 over multiple files) Though I've seen this happen with fewer
2) From the UI testing target press cmd-U to start the UI tests.
3) after anywhere from 3 or more (I've had up to 20 pass before this happens, but it does happen every time) tests run the simulator launches the app and just stays there. As above Xcode will report a SIGKILL (but the simulator doesn't change and the app is still running.

Expected Results:
I would expect tests to keep going

Actual Results:

Version:
OS X 10.10.5
Xcode Version 7.1 beta 3 (7B85)
## 

Product Version: 
Created: 2015-10-19T14:49:02.424890
Originated: 2015-10-19T00:00:00
Open Radar Link: http://www.openradar.me/23165183

**Comment by openradar-mirror** [comment]
Resolved: Duplicate of 22843418 (Open)
Modified: 2015-10-21T08:56:39.550390

**Comment by openradar-mirror** [comment]
Resolved: Duplicate of 22843418 (Open)
Modified: 2015-10-21T08:56:39.550390

**Comment by openradar-mirror** [comment]
Resolved: Duplicate of 22843418 (Open)
Modified: 2015-10-21T08:56:39.550390

**Comment by dyundt** [comment]
I am seeing this as well. Do you have a workaround?
